"""empty message

Revision ID: 1adbca13290a
Revises: 4333360f25f8
Create Date: 2022-12-16 16:21:11.683550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1adbca13290a"
down_revision = "4333360f25f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pictures", "tweet_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pictures", "tweet_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
