"""migrate

Revision ID: 1c6da90b31d7
Revises: 5c8dc90b0d59
Create Date: 2022-12-16 18:17:57.217963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6da90b31d7'
down_revision = '5c8dc90b0d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
