"""migrate

Revision ID: 2e029cc73a07
Revises: 781395c69f15
Create Date: 2022-12-16 10:21:27.391196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e029cc73a07'
down_revision = '781395c69f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
