"""empty message

Revision ID: 4333360f25f8
Revises: 9b040ae23f88
Create Date: 2022-12-16 21:54:27.551802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4333360f25f8'
down_revision = '9b040ae23f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
