"""migrate

Revision ID: 5625470d9301
Revises: 7cd55bf0a827
Create Date: 2022-12-18 14:21:05.245212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5625470d9301"
down_revision = "7cd55bf0a827"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
