"""migrate

Revision ID: 5c8dc90b0d59
Revises: 2e029cc73a07
Create Date: 2022-12-16 17:58:25.518553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8dc90b0d59'
down_revision = '2e029cc73a07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
