"""migrate

Revision ID: 73b797962bd5
Revises: a7d346f26bd8
Create Date: 2022-12-11 13:02:36.306417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73b797962bd5"
down_revision = "a7d346f26bd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
