"""migrate

Revision ID: 781395c69f15
Revises: 73b797962bd5
Create Date: 2022-12-12 21:39:46.175711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781395c69f15'
down_revision = '73b797962bd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
