"""migrate

Revision ID: 7cd55bf0a827
Revises: 1a0648455c38
Create Date: 2022-12-18 21:03:29.656342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cd55bf0a827"
down_revision = "1a0648455c38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
