"""empty message

Revision ID: 9b040ae23f88
Revises: e5fd0914dd76
Create Date: 2022-12-16 14:43:35.957927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b040ae23f88'
down_revision = 'e5fd0914dd76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
