"""empty message

Revision ID: e5fd0914dd76
Revises: 1c6da90b31d7
Create Date: 2022-12-16 21:29:28.248530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fd0914dd76'
down_revision = '1c6da90b31d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
